export { makeRemoteAddAccount } from './add-account/remote-add-account-factory'
export { makeRemoteAuthentication } from './authentication/remote-authentication-factory'
export { makeRemoteLoadSurveyList } from './load-survey-list/remote-load-survey-list-factory'
export { makeRemoteLoadSurveyResult } from './load-survey-result/remote-load-survey-result-factory'
export { makeRemoteSaveSurveyResult } from './save-survey-result/remote-save-survey-result-factory'
